basePath: /
definitions:
  model.RawSubscription:
    properties:
      end_date:
        example: 12-2025
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      subscription_id:
        example: 20
        type: integer
      user_id:
        example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
        type: string
    type: object
  model.Report:
    properties:
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API для управления подписками
  title: EM-test
  version: "1.0"
paths:
  /subscriptions:
    get:
      description: Отдает массив из всех подписок в базе; пустой json если подписок
        нет
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.RawSubscription'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Получение списка всех подписок из базы
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создаёт новую подписку из данных в теле запроса
      parameters:
      - description: Subscription info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.RawSubscription'
      produces:
      - application/json
      responses:
        "201":
          description: Subscription successfully created
          schema:
            $ref: '#/definitions/model.RawSubscription'
        "400":
          description: Incomplete/incorrect data input
          schema:
            type: string
        "409":
          description: Subscription already exists
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Cоздание новой подписки
      tags:
      - subscriptions
  /subscriptions/{sid}:
    delete:
      description: Удаляет подписки по ее SID из URL
      parameters:
      - description: SID подписки
        example: 20
        in: path
        name: sid
        required: true
        type: integer
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Subscription not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Удаление подписки по SID
      tags:
      - subscriptions
    get:
      description: Возвращает подписку в формате JSON по ее SID из URL
      parameters:
      - description: SID подписки
        example: 20
        in: path
        name: sid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.RawSubscription'
        "404":
          description: Subscription not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Получение подписки по SID
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет подписку по ее SID из URL, новые данные берутся из тела
        запроса
      parameters:
      - description: SID подписки
        example: 20
        in: path
        name: sid
        required: true
        type: integer
      - description: Subscription info
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.RawSubscription'
      produces:
      - application/json
      responses:
        "200":
          description: Subscription updated successfully
          schema:
            $ref: '#/definitions/model.RawSubscription'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Subscription not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Обновление подписки по ее SID
      tags:
      - subscriptions
  /subscriptions/report:
    get:
      description: Выдает сумму стоимости подписок по указанному периоду(конкретному
        месяцу в формате "07-2024"), пользователю и провайдеру; пользователь и провайдер
        не являются обязательными полями.
      parameters:
      - description: Период(конкретный месяц в формате 07-2024) для поиска подписок
          в активном статусе
        example: 07-2025
        in: query
        name: period
        required: true
        type: string
      - description: UID пользователя
        example: adjhdjfnv-njdfv889
        in: query
        name: uid
        type: string
      - description: Имя провайдера услуги
        example: Yandex
        in: query
        name: provider
        type: string
      responses:
        "200":
          description: Status OK
          schema:
            $ref: '#/definitions/model.Report'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Подсчет суммы подписок удовлетворяющим условиям
      tags:
      - subscriptions
swagger: "2.0"
